-- MySQL Script generated by MySQL Workbench
-- Fri May 13 20:22:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projeto1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projeto1` ;

-- -----------------------------------------------------
-- Schema projeto1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto1` DEFAULT CHARACTER SET utf8mb4 ;
USE `projeto1` ;

-- -----------------------------------------------------
-- Table `projeto1`.`tb_admin.online`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto1`.`tb_admin.online` ;

CREATE TABLE IF NOT EXISTS `projeto1`.`tb_admin.online` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(255) NOT NULL,
  `ultima_acao` DATETIME NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 56
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `projeto1`.`tb_admin.usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto1`.`tb_admin.usuarios` ;

CREATE TABLE IF NOT EXISTS `projeto1`.`tb_admin.usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `img` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `cargo` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `projeto1`.`tb_admin.visitas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto1`.`tb_admin.visitas` ;

CREATE TABLE IF NOT EXISTS `projeto1`.`tb_admin.visitas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(255) NOT NULL,
  `dia` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `projeto1`.`tb_site.categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto1`.`tb_site.categorias` ;

CREATE TABLE IF NOT EXISTS `projeto1`.`tb_site.categorias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `order_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `projeto1`.`tb_site.config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto1`.`tb_site.config` ;

CREATE TABLE IF NOT EXISTS `projeto1`.`tb_site.config` (
  `titulo` VARCHAR(255) NOT NULL,
  `nome_autor` VARCHAR(255) NOT NULL,
  `descricao` TEXT NOT NULL,
  `image1` VARCHAR(255) NOT NULL,
  `titulo_topicos1` VARCHAR(255) NOT NULL,
  `descricao1` TEXT NOT NULL,
  `image2` VARCHAR(255) NOT NULL,
  `titulo_topicos2` VARCHAR(255) NOT NULL,
  `descricao2` TEXT NOT NULL,
  `image3` VARCHAR(255) NOT NULL,
  `titulo_topicos3` VARCHAR(255) NOT NULL,
  `descricao3` TEXT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `projeto1`.`tb_site.noticias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto1`.`tb_site.noticias` ;

CREATE TABLE IF NOT EXISTS `projeto1`.`tb_site.noticias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `categoria_id` INT(11) NOT NULL,
  `data` DATE NOT NULL,
  `titulo` VARCHAR(25) NOT NULL,
  `conteudo` TEXT NOT NULL,
  `capa` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `order_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `projeto1`.`tb_site.objetivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto1`.`tb_site.objetivos` ;

CREATE TABLE IF NOT EXISTS `projeto1`.`tb_site.objetivos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `objetivos` TEXT NOT NULL,
  `order_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `projeto1`.`tb_site.slides`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto1`.`tb_site.slides` ;

CREATE TABLE IF NOT EXISTS `projeto1`.`tb_site.slides` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `slide` VARCHAR(255) NOT NULL,
  `order_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `projeto1`.`tb_site.sobre.assunto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto1`.`tb_site.sobre.assunto` ;

CREATE TABLE IF NOT EXISTS `projeto1`.`tb_site.sobre.assunto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `sobre` TEXT NOT NULL,
  `data` VARCHAR(255) NOT NULL,
  `order_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
